INSERT INTO EMPLOYEE(ID,PHONE_NO, NAME, DESIGNATION) VALUES ('1','042xxxxxx24','Sachin','ENGINEER');
INSERT INTO EMPLOYEE(ID,PHONE_NO, NAME, DESIGNATION) VALUES ('2','04xxxxxx08','Dhoni','ANALYST');
INSERT INTO EMPLOYEE(ID,PHONE_NO, NAME, DESIGNATION) VALUES ('3','04xxxxxx93','Raina','CHAPTER LEAD');
